# %challenges_get_classement_score%
# %challenges_is_started%
# %challenges_top_username_1%
# %challenges_top_count_2%
# %challenges_current_challenge_message%
# %challenges_current_challenge_count%
# %challenges_current_challenge_place%
# %challenges_current_challenge_countdown%

# in seconds, set 0 to disable and use command
interval: 20

# in seconds
timeout: 60

#number of second for countdown
countdown_number: 5

players_needed: 1

sound:
  messages: ENTITY_EXPERIENCE_ORB_PICKUP
  add: ENTITY_EXPERIENCE_ORB_PICKUP
  remove: BLOCK_ANVIL_BREAK

# if the hour isn't into the list the challenges isn't start, useless if interval = 0, set [] to disable
whitelisted_hours: []

blacklisted_world:
  - invest

#challenges_example:
#  '0':
#    message: "Casser des Roches"
#    challenge: "BLOCK_BREAK"
#    requirement:
#      - "STONE:0"
#  '1':
#    message: "Tuer des zombies"
#    challenge: "ENTITY_DEATH"
#    requirement:
#      - "ZOMBIE"
#  '2':
#    message: "Pêcher des Objets/Poissons"
#    challenge: "FISHING"
#  '3':
#    message: "Enchanter des objets"
#    challenge: "ENCHANT_ALL"
#  '4':
#    message: "Enchanter des Pelles en fer"
#    challenge: "ENCHANT_ALL"
#    requirement:
#      - "IRON_SHOVEL"
#  '5':
#    message: "Manger des Légumes"
#    challenge: "CONSUME"

challenges:
  '0':
    message: "Casser des Roches"
    challenge: "BLOCK_BREAK"
    requirement:
      - "STONE:0"

rewards:
  give_for_all_reward_to_top: true
  for_all:
    message: "1 Diamant"
    commands:
      - "give %player% diamond 1"
  add_all_top_into_db: true
  top:
    '1':
      message: "1 terre"
      commands:
        - "give %player% dirt 1"
    '2':
      message: "1 terre"
      commands:
        - "give %player% dirt 1"

messages:
  placeholders:
    current_challenge_countdown:
      started: "{0} {1}"
      stop: "&c✖"
  commands:
    no_permission: "&fCommande inconnue."
    help:
      - "&7&m------------------&8[&6Help Panel&8]&7&m------------------"
      - "{!challenges.command.start}&6/clgs start &estart a challenge !"
      - "{!challenges.command.stop}&6/clgs stop &estop the current challenge !"
      - "{!challenges.command.start_interval}&6/clgs start_interval &estart challenge interval !"
      - "{!challenges.command.stop_interval}&6/clgs stop_interval &estop challenge interval !"
      - "{!challenges.command.reload}&6/clgs reload &ereload the plugin !"
      - "&7&m----------------------------------------------"
    success_start: "&7[&c&lES&7] Le challenge a été lancé avec succès !"
    success_stop: "&7[&c&lES&7] Le challenge a été stoppé avec succès !"
    success_start_interval: "&7[&c&lES&7] L'interval des challenges a été lancé avec succès !"
    success_stop_interval: "&7[&c&lES&7] L'interval des challenges a été stoppé avec succès !"
    success_reload: "&7[&c&lES&7] Le plugin vient d'être reload !"
  global:
    none: "Aucun"
    none2: "Aucune"
    second: "seconde"
    seconds: "secondes"
    minute: "minute"
    minutes: "minutes"
    hour: "heure"
    hours: "heures"
  title:
    start:
      stay: 4
      fadeInTick: 10
      fadeOutTick: 20
      title: "Défi !"
      subtitle: "Vous avez {0} {1} pour : &a{2} !"
    countdown:
      title: "Défi !"
      subtitle: "Défi lancé dans {0} {1} !"
  action_bar:
    message: "{0} : {1} - {2} {3} restantes !"
    countdown: "Défi lancé dans {0} {1} !"
  chat:
    start_message: "&7[&c&lES&7] Vous avez {0} {1} pour : &a{2} !&7 Soyez le meilleur !"
    no_player: "&7[&c&lES&7] Aucun joueur n'a fait le défi !"
    top:
      template: "- {0}, {1} score : {2}"
      message:
        - "test"
        - "{0}"
  rewards:
    for_all: "&7[&c&lES&7] Vous avez participé au défi, vous gagnez {0} !"
    top: "&7[&c&lES&7] Vous avez participé au défi, et vous êtes &aTOP {0} &7! Vous gagnez : {1} !"