# in minutes
interval: 1
# in minutes
timeout: 1

sound:
  messages: ENTITY_EXPERIENCE_ORB_PICKUP
  add: ENTITY_EXPERIENCE_ORB_PICKUP
  remove: BLOCK_ANVIL_BREAK

# if the hour isn't into the list the challenges isn't start
whitelisted_hours:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 00
  - 01

blacklisted_world:
  - invest

challenges_example:
  '0':
    message: "Casser des Roches"
    challenge: "BLOCK_BREAK"
    requirement:
      - "STONE:0"
  '1':
    message: "Tuer des zombies"
    challenge: "ENTITY_DEATH"
    requirement:
      - "ZOMBIE"
  '2':
    message: "Pêcher des Objets/Poissons"
    challenge: "FISHING"
  '3':
    message: "Enchanter des objets"
    challenge: "ENCHANT_ALL"
  '4':
    message: "Enchanter des Pelles en fer"
    challenge: "ENCHANT_ALL"
    requirement:
      - "IRON_SHOVEL"
  '5':
    message: "Manger des Légumes"
    challenge: "CONSUME"

challenges:
  '0':
    message: "Casser des Roches"
    challenge: "BLOCK_BREAK"
    requirement:
      - "STONE:0"

rewards:
  give_for_all_reward_to_top: true
  for_all:
    - "give %player% diamond 1"
  top:
    '1':
      - "give %player% dirt 1"
    '2':
      - "second"

messages:
  global:
    second: "seconde"
    seconds: "secondes"
    minute: "minute"
    minutes: "minutes"
    hour: "heure"
    hours: "heures"
  action_bar:
    message: "{0} : {1} - {2} {3} restantes !"
    countdown: "Défi lancé dans {0} {1} !"
  chat:
    start_message: "&7[&c&lES&7] Vous avez {0} minutes pour : &a{1} !&7 Soyez le meilleur !"
    no_player: "&7[&c&lES&7] Aucun joueur n'a fait le défi !"
    top:
      template: "- {0}, {1} score : {2}"
      message:
        - "test"
        - "{0}"
  rewards:
    for_all: "&7[&c&lES&7] Vous avez participé au défi, vous gagnez quelques récompenses !"
    top: "&7[&c&lES&7] Vous avez participé au défi, et vous êtes &aTOP {0} &7! Vous gagnez des récompenses !"