name: Challenges
version: 1.0.1
author: nivcoo
main: fr.nivcoo.challenges.Challenges
api-version: 1.13
softdepend: [ PlaceholderAPI, WildTools, WildStacker ]
commands:
  clgs:
    description: Challenges Command
permissions:
  challenges.commands:
    default: op
    description: command
  challenges.command.start:
    default: op
    description: Start Challenge
  challenges.command.stop:
    default: op
    description: Stop Current Challenge
  challenges.command.end:
    default: op
    description: Stop Current Challenge with rewards
  challenges.command.start_interval:
    default: op
    description: Start Challenge Interval
  challenges.command.stop_interval:
    default: op
    description: Stop Challenge Interval
  challenges.command.reload:
    default: op
    description: Reload the Plugin
  challenges.command.delete_datas:
    default: op
    description: Delete all db datas