name: Challenges
version: 1.0.0
author: nivcoo
main: fr.nivcoo.challenges.Challenges
softdepend: [PlaceholderAPI]
commands:
  clgs:
    description: Challenges Command
permissions:
  challenges.help:
    default: op
    description: help
  challenges.command.start:
    default: op
    description: Start Challenge
  challenges.command.stop:
    default: op
    description: Stop Current Challenge
  challenges.command.end:
    default: op
    description: Stop Current Challenge with rewards
  challenges.command.start_interval:
    default: op
    description: Start Challenge Interval
  challenges.command.stop_interval:
    default: op
    description: Stop Challenge Interval
  challenges.command.reload:
    default: op
    description: Reload the Plugin