name: Challenges
version: 1.0.0
author: nivcoo
main: fr.nivcoo.challenges.Challenges
softdepend: [PlaceholderAPI]
commands:
  clgs:
    description: Challenges Command
permissions:
  challenges.help:
    default: op
    description: help
  challenges.start:
    default: op
    description: Start Challenge
  challenges.stop:
    default: op
    description: Stop Current Challenge
  challenges.start_interval:
    default: op
    description: Start Challenge Interval
  challenges.stop_interval:
    default: op
    description: Stop Challenge Interval